Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Profile/ProfileModel.swift, Clokey/Clokey/Sources/Feature/Profile/ProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/ProfileViewController.swift
- 화면 UI 구현
- 배경사진 및 프로필 사진, 프로필 내용 UI 배치
- 옷장 및 기록 UI 배치
- 옷장 파트의 3개 옷은 KingFisher로 이미지 불러옴
=> [Feature] 내 프로필 뷰 UI 구현

Clokey/Clokey/Application/SceneDelegate.swift, Clokey/Clokey/Sources/Feature/Main/MainView.swift, Clokey/Clokey/Sources/Feature/Main/MainViewController.swift
- 옷추가 화면으로 네비게이션 띄우기 위한 sceneDelgate 및 MainViewController 수정
=> [Feature] 메인 VC 및 SceneDelegate 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Nofitication/Model/NotificationViewModel.swift, Clokey/Clokey/Sources/Feature/Nofitication/VIews/NotificationView.swift, Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift, Clokey/Clokey/Sources/Feature/Search/Model/SearchResultModel.swift, Clokey/Clokey/Sources/Feature/Search/Model/UserModel.swift, Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift, Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchViewController.swift, Clokey/Clokey/Sources/Network/notification/Endpoints/NotificationEndpoints.swift, Clokey/Clokey/Sources/Network/notification/Response/NotificationResponseDTO.swift, Clokey/Clokey/Sources/Network/notification/Service/NotificationService.swift, Clokey/Clokey/Sources/Network/search/Endpoints/SearchEndpoint.swift, Clokey/Clokey/Sources/Network/search/Response/SearchResponseDTO.swift
-알림 API 연동 완료 하였습니다. 전체 읽음 , 개별읽음 처리 가능합니다.
- 알림 목록 조회 API연동하여, 서버에서 받아오는 알림을 목록처럼 볼수있게 구현하였습니다
- 개별적으로 알림을 눌렀을때 읽음 처리되는 기능과, 새로고침을 했을때 전체 읽음 되는 기능을 API연동을 통하여 구현하였습니다.
- 뒤로가기 버튼 뿐만 아니라, 화면을 왼쪽에서 오른쪽으로 스와이프하면 뒤로가기가 가능하도록 구현하였습니다 
현재 스와이프 하여 뒤로가기 기능을 더욱 예쁘게 만들기 위해서는 RxSwif,  RxCocoa, RxGesture 이 세 패키지를 통하여 구현하여야 합니다. 이부분은 먼저 다른 기능들이 구현이 된후 보완하도록 하겠습니다
=> [Feature] 알림 읽음 처리 API 연동 완료

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/CalendarViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/Calendar/FriendsCalendarDetailViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Network/notification/Response/NotificationResponseDTO.swift, Clokey/Clokey/Sources/Network/notification/Service/NotificationService.swift
홈 페이지에서 세부 기록 페이지 띄우기 및 댓글 알림
- 댓글 띄우고 알림 보내기 성공
- 세부 기록 페이지 프로필 사진 크기 수정
일단 홈 소식의 첫번째 항목만 연결해놨습니다.
=> [Feature] 홈 페이지에서 세부 기록 페이지 띄우기 및 댓글 알림

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift, Clokey/Clokey/Sources/Feature/Main/MainViewController.swift, Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift, Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowerUserCell.swift, Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowingUserCell.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserCell.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowerUserModel.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowingUserCell.swift, Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
- 팔로우/팔로잉 목록조회 팔로우 버튼 활성화
- 목록조회에서의 팔로우 버튼을 활성화
- 상대방의 팔로우/팔로잉 목록조회에서 자신의 목록에는 팔로우 버튼 숨김처리
=> [Fix] 팔로우/팔로잉 목록조회 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/PhotoTagView.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift, Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift, Clokey/Clokey/Sources/Network/members/Response/MembersLoginResponseDTO.swift
- 캘린더 기록하기 버그 수정 및 상단바 수정
- 기록하다 뒤로가기 경고 띄우기
- 친구 프로필에서 옷장 보기에서 상단 네비게이션 바 수정
=> [Feature] 캘린더 기록하기 버그 수정 및 상단바 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json, Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json, Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift, Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift, Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
-팔로우 목록 조회 새로고침 수정 
- 프로필 설정 뷰 수정
- 팔로우 목록 조회 새로고침 버그 수정
-프로필 설정 뷰 수정
=> [FIX] 팔로우 목록 조회 새로고침 수정 및 프로필 설정 뷰 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Resources/Assets.xcassets/2D ICONS/dot3_icon.imageset/Contents.json, Clokey/Clokey/Resources/Assets.xcassets/Compoenets_icon/erase_icon.imageset/Contents.json, Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift
=> [FIX] 내 옷장 새로고침 추가

Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
=> [FIX] 팝업창 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Main/MainViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
- 뒤로가기 수정 및 팝업창 수정
- 옷추가 첫페이지에서 뒤로가기 시 홈에서의 새로고침 수정
- 팝업창 닫기 시 다른 화면 눌러도 닫히도록 수정
=> [FIX] 뒤로가기 수정 및 팝업창 수정

Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Main/MainViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift, Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift, Clokey/Clokey/Sources/Network/Clothes/Request/AddClothesRequestDTO.swift, Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift, Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
- 슬라이드 제스처 및 로딩 창 생성
- 옷 재추가 시 화면에서 이전 슬라이드를 했을 때, 홈화면으로 이동하고 자동 새로고침이 되도록 함.
- 홈화면, 프로필 화면 띄울 시, 서버로부터 불러오는 시간동안 흰색 바탕 화면 띄우기
- 모든 뷰에서 이전 제스처 시 홈화면으로 가는 버그 수정
=> [FIX] 슬라이드 제스처 및 로딩 창 생성

Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
-  PICK 네트워크 불러오는 과정에서의 뷰 수정
- PICK에서 네트워크 불러오는 과정에서의 로딩 뷰의 생명주기를 수정
-
=> [FIX] PICK 네트워크 불러오는 과정에서의 뷰 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift
- Pick 날씨 불러오기 수정
- 현재 날씨를 불러올때도 옷추천 네트워크가 불러와지도록 수정 
-
=> [FIX] Pick 날씨 불러오기 수정

Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Success/SuccessView.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift, Clokey/Clokey/Sources/Network/Clothes/Endpoints/ClothesEndpoint.swift, Clokey/Clokey/Sources/Network/Clothes/Service/ClothesService.swift
- 내옷장 팝업뷰에서 옷 수정하기로 넘어가기
- 팝업창의 옷 편집 누를 시 옷 수정 뷰로 넘어가기
- 저장된 옷 정보를 옷 수정 뷰에 정보를 띄우기
- 마지막 창에서 완료 버튼 누를 시 정보 수정
=> [Feature] 옷 수정하기

Clokey/Clokey/Sources/Common/Components/Category/AddCategoryViewController.swift, Clokey/Clokey/Sources/Common/Components/CustomSearchField.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Category/CategoryViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailView.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift
설정화면 계정 탭 추가
- 설정뷰 UI 수정 및 계정 탭 추가
- settingView ptdFont 추가
=> [Feature] 설정 뷰 계정 탭 추가

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothesView.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/lastAddView.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/Slider.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/HomeViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/Views/HomeView.swift, Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift, Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/More/UpdateFriendCalendarView.swift, Clokey/Clokey/Sources/Feature/Home/Views/PickViews/PickView.swift, Clokey/Clokey/Sources/Feature/Home/Views/PickViews/Popup/PickPopUpView.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/CustomBottomSheetViewController.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
- 공통 네비게이션바로 수정
- 피그마 새로 수정 뷰 레이아웃으로 수정
- 옷추가/옷수정, 프로필 수정 뷰 네비게이션 바를 공통 네비게이션바로 수정
- 새로 수정된 뷰대로 레이아웃 수정
=> [Fix] 새로 수정된 뷰 수정 및 공통 네비게이션바로 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Clokey.entitlements
WeatherKit 추가 
- weatherKit Capability 추가 및 세팅 완료
=> [Feature] WeatherKit 추가

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Supporting Files/Info.plist
- TestFlight에 앱 아이콘이 안뜨는 버그 수정
- 테스터의 최소 버전을 고려해서 17.2로 버전 수정
1차 TestFlight 버전 입니다.
- 앱 아이콘을 등록했습니다.
- 테스터의 아이폰의 최소 버전에 맞춰 17.2로 버전을 수정했습니다.
=> [Feature] 1차 TestFlight 버전 업로드

Clokey/Clokey/Sources/Common/Components/CustomTotalSegmentView.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift
대댓글 알림 추가 및 옷장 세부 세그먼트 버튼 색 변경
- 대댓글 시, 기록 주인에게도 알림 추가
- 옷장의 세부 카테고리 버튼 색 변경
=> [Fix] 대댓글 알림 추가 및 옷장 세부 세그먼트 버튼 색 변경

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Common/Components/CustomNavigationBar.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/AddProfile/AddProfileView.swift, Clokey/Clokey/Sources/Feature/AddProfile/AddProfileViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Main/MainViewController.swift, Clokey/Clokey/Sources/Feature/Profile/EditProfile/EditProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/MyFollowList/MyFollowListViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
- 프로필 상단 뷰 수정
- 상대 프로필 상단에 네비게이션 바 수정
- 내 프로필 상단 뷰 수정
=> [Fix] 새로 수정된 프로필 뷰 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteViewController.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportViewController.swift, Clokey/Clokey/Sources/Common/Components/Report/ReportSuccessView.swift, Clokey/Clokey/Sources/Common/Components/Report/ReportSuccessViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupView.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Popup/PopupViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Settings/SettingView.swift, Clokey/Clokey/Sources/Feature/Profile/Settings/SettingViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
- 팝업창 수정
- 세팅 뷰 네비게이션으로 수정
- 팝업창 그림자 추가
- 신고 완료 후 플로우 수정
-
=> [Fix] 새로 수정 페이지 뷰 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteView.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportCompleteViewController.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportView.swift, Clokey/Clokey/Sources/Common/Components/Report/AccountReportViewController.swift, Clokey/Clokey/Sources/Common/Components/Report/ReportReason.swift, Clokey/Clokey/Sources/Common/Components/Report/ReportReasonView.swift
report 파일 수정
- 서버에서 주는 값에 맞춰서 파일 수정
- 일단은 계정 신고 기준 UI 설정 완료
- 댓글/기록을 위해 수정이 필요합니다. 빠른 시일 내에 추가해서 올릴게요.
=> [Fix] report 파일 수정

Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Services/WeatherAPI.swift
- 날씨 데이터 불러오기 수정
- 날씨 정보를 불러오기 위해 위치정보를 전달 시 위치정보를 현재 위치의 주소가 아닌 위도/경도 값을 전달해 위치 정보를 보내는 것으로 수정
-
=> [Fix] 날씨 정보 불러오기 수정

Clokey/Clokey/Sources/Common/Components/Report/CustomReportCompleteViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsActionSheetViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift, Clokey/Clokey/Sources/Network/members/Endpoints/MembersEndpoint.swift, Clokey/Clokey/Sources/Network/members/Service/MembersService.swift
사용자 차단 기능 구현
- 차단 API 세팅 완료
- 기록에서 사용자 차단 기능 구현 완료
- 기록의 댓글에서 사용자 차단 기능 구현 완료
- 신고하기 내용 입력 후, 키보드 내려가지 않는 버그 수정 완료
@Funital CalendarCommentViewController파일의 177-234줄을 참고하시면 됩니다.
차단을 완료 후에 어떤 화면을 띄워야할지 PM 님께 문의드려놓은 상태입니다.
=> [Feature] 사용자 차단 기능 구현

Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift, Clokey/Clokey/Sources/Feature/Agreement/AgreementViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/CalendarDetailViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/FriendsCalendarDetailViewController.swift, Clokey/Clokey/Sources/Feature/Nofitication/ViewControllers/NotificationViewController.swift, Clokey/Clokey/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift, Clokey/Clokey/Sources/Feature/Search/view/SearchView.swift
NotificationViewModel
NotificationViewController
SearchView
SearchResultViewController
AgreementViewController
ThickViewController 에 있는 경고문 제거
안쓰이는 변수는 _ 처리를 하고, deprecated 된 문법들을 고쳤습니다
=> [Bug] 경고문 제거

Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentView.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CalendarCommentViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/Commnet/CommentCell.swift, Clokey/Clokey/Sources/Network/notification/Endpoints/NotificationEndpoints.swift
대댓글 버그 수정 및 경고문 제거 
- 대댓글 프로필을 눌러도 댓글의 프로필로 이동하던 버그 수정
- 이슈로 인해 빌드 시 뜨는 경고문 제거
=> [Fix] 대댓글 버그 수정 및 경고문 제거 

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddClothViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Home/Views/NewsViews/Main/NewsView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift
- 차단 API 추가
- 프로필 뷰 수정
- 상대방 계정에서 차단 및 차단 해제 시의 api 연결
- 상대방 팔로워/팔로잉 목록에서 내 계정 선택시 연결되는 뷰 수정
-
=> [Feat/FIX] 차단 API 추가 및 프로필 뷰 수정

Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/CustomGalleryViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/Photo/PhotoEditViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift
기록하기 페이지에 사진이 불러와지지 않음
- 커스텀 갤러리에서 사진 선택/편집 후, 기록 페이지로 왔을 때 사진이 불러와지지 않는 버그 수정
=> [Fix] 기록하기에서 사진이 뜨지 않는 버그 수정

Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
- 차단 해제 시 누르자마자 띄워지는 뷰 버그 수정
-
=> [Fix] 차단 해제 시 뷰 버그 수정

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Common/Components/ImagePickViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/AddImage/LastAddViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Temperature/WeatherChooseViewController.swift, Clokey/Clokey/Sources/Feature/AddCloth/AddCloth/Thick/ThickViewController.swift, Clokey/Clokey/Sources/Feature/Home/Cells/UpdateFriendCalendarCollectionViewCell.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/Pick/PickViewController.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/My/ProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift, Clokey/Clokey/Sources/Feature/Profile/YourFollowList/YourFollowListViewController.swift, Clokey/Clokey/Sources/Network/home/Response/OneYearAgoHistoriesResponseDTO.swift, Clokey/Clokey/Sources/Network/members/Response/MembersInfoResponseDTO.swift
- 프로필 사진 선택 동작 추가
- 회원조회에서 isMe, isBlocking 추가
- 프로필 사진 선택 시 사진만 보이도록 설정
- isMe를 통해 상대방의 기록이나 팔로워 목록에서 내 계정의 뷰 수정
=> [Fix] 회원조회 및 프로필 수정

Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendCalendarViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/More/UpdateFriendClothesViewController.swift
- 페이징 처리 과정에서의 버그 수정
#80
소식 더보기 버그 수정
- 페이징 처리 과정에서 계속 업데이트 되는 버그 수정
- 페이지를 3개까지만으로 수정
-
=> [Fix] 소식 더보기 버그 수정

Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
- 차단 프로필 뷰 수정
- 차단 프로필 뷰 띄울 때 회원 조회와 동시에 isBlock이 적용되도록 수정
-
=> [Fix] 차단 프로필 뷰 수정

Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/PopUpDropdownViewController.swift, Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditViewController.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoViewController.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerViewController.swift
#132
옷장 내 네트워크 오류 처리
- SmartSummationViewController, ClosetViewController, ClosetPopUpViewController, PopupDropdownViewController, DisplayAllViewController, DrawerEditViewController, DrawerInfoViewController, DrawerViewController에서 오류 처리
=> [Fix] 옷장 내 네트워크 오류 처리

Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpViewController.swift
#137
- 팝업창 폰트 크기 및 텍스트 상이한 거 수정
- Url 부분 없을 시 지정없음으로 수정
- 폰트크기 16 -> 12
=> fix: 팝업창 폰트 크기 및 텍스트 상이한 거 수정

Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/TagCloth/TagClothView.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetCollectionViewCell.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetView.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/ClosetViewController.swift, Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllView.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerEditView.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoView.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerView.swift
기종 마다 옷장 비율 관련 문제 해결 
- 옷장을 띄우는 모든 뷰에 유동적 계산 로직 추가
16프맥이 이쁘게 나오지는 않지만,, 3등분이 안되거나 겹쳐서 안보이는 버그는 없습니다..!
=> [Fix] 옷장 비율 관련 문제 해결 

Clokey/Clokey.xcodeproj/project.pbxproj, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/ArrangeClosetViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetPopUp/ClosetPopUpView.swift, Clokey/Clokey/Sources/Feature/Closet/Drawer/DrawerInfoViewController.swift, Clokey/Clokey/Sources/Network/Clothes/Response/InquiryClothesDetailResponseDTO.swift
옷장 부분 API수정됨에 따라 관련 부분 수정
#137
- closet response DTO 수정
- 옷장정리, 스마트요약 닉네임 불러오는 방식 수정
=> [Fix] 스마트 요약, 옷장 정리 부분 수정

Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/ContentInputView.swift, Clokey/Clokey/Sources/Feature/Calendar/AddOOTD/RecordOOTDViewController.swift, Clokey/Clokey/Sources/Feature/Calendar/CustomCalendar/CalendarDetails/tagClothList/RecordTagClothViewController.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationView.swift, Clokey/Clokey/Sources/Feature/Closet/ClosetMain/Banner/SmartSummationViewController.swift, Clokey/Clokey/Sources/Feature/Closet/DisplayAll/DisplayAllViewController.swift, Clokey/Clokey/Sources/Feature/Home/ViewControllers/News/Main/NewsViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowCalendarViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileActionViewController.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileView.swift, Clokey/Clokey/Sources/Feature/Profile/Your/FollowProfileViewController.swift
차단/비공개 계정 버그 수정
- 차단한 계정의 더보기 버튼과 옷장 구경하기가 뜨는 버그 수정
- 프로필 뷰 비공개 계정 UI 적용 안되는 버그 수정
- 본인+비공개 계정일 경우 오버레이가 안꺼지는 버그 수정
- 기록 편집에서 내용을 수정하지 않으면 날라가는 버그 수정
=> [Fix] 차단/비공개 계정 버그 수정
